server:
  port: 8082
spring:
  application:
    name: redis
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/redis?createDatabaseIfNotExist=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Saurabh@645}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      port: 6379
      host: localhost


